---
- name: Add the service (type LoadBalancer) for control plane
  vars:
    svcname: "{{ ai_ocp_vmname_control_plane_prefix }}-svc"
  kubernetes.core.k8s:
    definition: "{{ lookup('ansible.builtin.template', 'control_plane_svc.yaml.j2') | from_yaml }}"
    wait: true
    wait_timeout: 300

- name: Add the service (type LoadBalancer) for workers
  vars:
    svcname: "{{ ai_ocp_vmname_worker_prefix }}-svc"
    role: "control-plane"
  kubernetes.core.k8s:
    definition: "{{ lookup('ansible.builtin.template', 'workers_svc.yaml.j2') | from_yaml }}"
    wait: true
    wait_timeout: 300

- name: Wait for the LoadBalancer value - control plane
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: "{{ ai_ocp_vmname_control_plane_prefix }}-svc"
    namespace: "{{ ai_ocp_namespace }}"
  register: r_svc_control_plane
  until: r_svc_control_plane.resources[0].status.loadBalancer.ingress[0].ip | default('') != ''
  retries: 10
  delay: 2

- name: Add A DNS record - api (Route53)
  when: route53_aws_access_key_id is defined
  amazon.aws.route53:
    state: present
    aws_access_key_id: "{{ route53_aws_access_key_id }}"
    aws_secret_access_key: "{{ route53_aws_secret_access_key }}"
    hosted_zone_id: "{{ route53_aws_zone_id }}"
    record: "api.{{ cluster_name}}.{{ cluster_dns_zone }}"
    zone: "{{ cluster_dns_zone  }}"
    value: "{{ r_svc_control_plane.resources[0].status.loadBalancer.ingress[0].ip }}"
    type: A
  register: r_route53_add_record
  until: r_route53_add_record is success
  retries: 20
  delay: 30

- name: Add A DNS record - api-int (Route53)
  when: route53_aws_access_key_id is defined
  amazon.aws.route53:
    state: present
    aws_access_key_id: "{{ route53_aws_access_key_id }}"
    aws_secret_access_key: "{{ route53_aws_secret_access_key }}"
    hosted_zone_id: "{{ route53_aws_zone_id }}"
    record: "api-int.{{ cluster_name}}.{{ cluster_dns_zone }}"
    zone: "{{ cluster_dns_zone  }}"
    value: "{{ ai_network_prefix + '.100' if control_plane_instance_count | int > 1 else ai_network_prefix + '.10' }}"
    type: A
  register: r_route53_add_record
  until: r_route53_add_record is success
  retries: 20
  delay: 30

- name: Add A DNS record - apps (Route53)
  when: route53_aws_access_key_id is defined
  amazon.aws.route53:
    state: present
    aws_access_key_id: "{{ route53_aws_access_key_id }}"
    aws_secret_access_key: "{{ route53_aws_secret_access_key }}"
    hosted_zone_id: "{{ route53_aws_zone_id }}"
    record: "*.apps.{{ cluster_name}}.{{ cluster_dns_zone }}"
    zone: "{{ cluster_dns_zone  }}"
    value: "{{ r_svc_control_plane.resources[0].status.loadBalancer.ingress[0].ip }}"
    type: A
  register: r_route53_add_record
  until: r_route53_add_record is success
  retries: 20
  delay: 30

- name: Add A dns record - masters
  when: cluster_dns_server is defined
  community.general.nsupdate:
    server: >-
      {{ cluster_dns_server
      | ansible.utils.ipaddr
      | ternary(cluster_dns_server, lookup('community.general.dig', cluster_dns_server))
      }}
    zone: "{{ cluster_dns_zone }}"
    record: "api.{{ cluster_name}}"
    type: A
    ttl: 30
    port: "{{ cluster_dns_port | d('53') }}"
    value: "{{ r_svc_control_plane.resources[0].status.loadBalancer.ingress[0].ip }}"
    key_name: "{{ ddns_key_name }}"
    key_secret: "{{ ddns_key_secret }}"
    key_algorithm: "hmac-sha256"

- name: Add A dns record - masters
  when: cluster_dns_server is defined
  community.general.nsupdate:
    server: >-
      {{ cluster_dns_server
      | ansible.utils.ipaddr
      | ternary(cluster_dns_server, lookup('community.general.dig', cluster_dns_server))
      }}
    zone: "{{ cluster_dns_zone }}"
    record: "api-int.{{ cluster_name}}"
    type: A
    ttl: 30
    port: "{{ cluster_dns_port | d('53') }}"
    value: "{{ ai_network_prefix + '.100' if control_plane_instance_count | int > 1 else ai_network_prefix + '.10' }}"
    key_name: "{{ ddns_key_name }}"
    key_secret: "{{ ddns_key_secret }}"
    key_algorithm: "hmac-sha256"

- name: Add A dns record - workers
  when: cluster_dns_server is defined
  community.general.nsupdate:
    server: >-
      {{ cluster_dns_server
      | ansible.utils.ipaddr
      | ternary(cluster_dns_server, lookup('community.general.dig', cluster_dns_server))
      }}
    zone: "{{ cluster_dns_zone }}"
    record: "*.apps.{{ cluster_name}}"
    type: A
    ttl: 30
    port: "{{ cluster_dns_port | d('53') }}"
    value: "{{ r_svc_control_plane.resources[0].status.loadBalancer.ingress[0].ip }}"
    key_name: "{{ ddns_key_name }}"
    key_secret: "{{ ddns_key_secret }}"
    key_algorithm: "hmac-sha256"
