---
_cluster_name: "{{ cluster_name }}"
ai_pull_secret: "{{ ocp4_ai_pull_secret | to_json | to_json if ocp4_ai_pull_secret is mapping else ocp4_ai_pull_secret | to_json }}"
ai_offline_token: "{{ ocp4_ai_offline_token }}"

ai_ssh_authorized_key: "{{ lookup('ansible.builtin.file', hostvars.localhost.ssh_provision_pubkey_path) }}"
ai_cluster_name: "{{ guid }}"
ai_cluster_version: "{{ host_ocp4_installer_version | default('4.19') }}"
ai_cluster_iso_type: minimal-iso
ai_ocp_output_dir: "~{{ ansible_user }}"
ai_ocp_namespace: "{{ sandbox_openshift_namespace | default(config + '-' + guid)}}"
ai_storage_class: ocs-storagecluster-ceph-rbd
ai_local_storageclass: hostpath-csi
ai_network_prefix: "10.10.10"
ai_network_prefix_length: 24
ai_service_network_cidr: "172.31.0.0/16"
ai_cluster_network_cidr: "10.132.0.0/14"
ai_network_mtu: 1500
# This variable is used to configure the role and the installation disk
ai_configure_hosts: []

# Control plane
ai_control_plane_cores: 8
ai_control_plane_memory: 16Gi
ai_control_plane_root_disk_size: 100Gi
ai_control_plane_etcd_disk_size: 8Gi
ai_control_plane_extra_disks: []
ai_control_plane_macs: []
ai_control_plane_macs2: []
ai_attach_control_plane_macs: {}
ai_attach_control_plane_networks: []
ai_ocp_vmname_control_plane_prefix: "control-plane-{{ _cluster_name }}"

# Workers
ai_workers_cores: 16
ai_workers_memory: 64Gi
ai_workers_root_disk_size: 100Gi
ai_workers_extra_disks: []
ai_workers_macs: []
ai_workers_macs2: []
ai_attach_workers_macs: {}
ai_attach_workers_networks: []
ai_ocp_vmname_worker_prefix: "worker-{{ _cluster_name }}"

ai_ocp_vmname_sno: "sno-{{ _cluster_name }}"

# Additional MachineConfigs to be added to the cluster
ai_machineconfigs: []
# ai_machineconfigs:
# - apiVersion: machineconfiguration.openshift.io/v1
#   kind: MachineConfig
#   metadata:
#     labels:
#       machineconfiguration.openshift.io/role: worker
#     name: 99-openshift-machineconfig-worker-psi-karg
#   spec:
#     kernelArguments:
#     - psi=1
