---
- name: Step 005 - Post software
  hosts: bastions
  become: false
  gather_facts: false
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/{{ cluster_name }}/auth/kubeconfig
  tasks:
  - name: Print post software
    ansible.builtin.debug:
      msg: "Post-Software Steps starting"

  - name: Remove AWS Credentials from bastion
    when:
    - cloud_provider == 'aws'
    - host_ocp4_deploy_installation_method != 'rosa'
    ansible.builtin.file:
      path: "/home/{{ ansible_user }}/.aws/credentials"
      state: absent

  - name: Remove Azure Credentials directory from bastion
    when: cloud_provider == 'azure'
    ansible.builtin.file:
      path: "/home/{{ ansible_user }}/.azure"
      state: absent

  - name: Remove the openshift-installer GCP Credentials directory from bastion
    when: cloud_provider == 'gcp'
    ansible.builtin.file:
      path: "/home/{{ ansible_user }}/.gcp"
      state: absent

  - name: Remove gcloud CLI Credentials directory from bastion
    when: cloud_provider == 'gcp'
    ansible.builtin.file:
      path: "/home/{{ ansible_user }}/.config/gcloud"
      state: absent

  - name: Print GCP access user info
    when:
    - cloud_provider == "gcp"
    - agnosticd_open_environment | default(false) | bool
    ansible.builtin.include_role:
      name: open-env-gcp-user-info

- name: Step 005.2 - Post install cluster configuration
  hosts: localhost
  gather_facts: false
  become: false
  environment:
    KUBECONFIG: "{{ hostvars.localhost.output_dir }}/{{ config }}_{{ guid }}_kubeconfig"
  tasks:
  - name: Wait for OpenShift API to be reachable
    kubernetes.core.k8s_info:
      api_version: config.openshift.io/v1
      kind: Infrastructure
      name: cluster
    register: r_api_check
    retries: 30
    delay: 10
    until: r_api_check is success

  - name: Setup cluster-admin service account
    when: openshift_cluster_admin_service_account_enable | bool
    ansible.builtin.include_role:
      name: openshift_cluster_admin_service_account

- name: Step 005.3 - Deploy Workloads
  ansible.builtin.import_playbook: workloads.yml

# - name: Step 005.4 Clean up Google SDK
#   hosts: localhost
#   gather_facts: false
#   become: false
#   tasks:
#   - name: Remove Google Cloud SDK
#     when: cloud_provider == "gcp"
#     ansible.builtin.file:
#       path: "{{ output_dir }}/google-cloud-sdk"
#       state: absent

- name: Step 005.5 - Remove mint-mode cloud provider credentials
  hosts: localhost
  gather_facts: false
  become: false
  environment:
    KUBECONFIG: "{{ hostvars.localhost.output_dir }}/{{ config }}_{{ guid }}_kubeconfig"
  tasks:
  - name: Remove mint-mode cloud provider credentials
    when:
    - remove_mint_mode_cloud_provider_credentials | bool
    - host_ocp4_deploy_installation_method != 'rosa'
    kubernetes.core.k8s:
      state: absent
      api_version: v1
      kind: Secret
      name: "{{ item }}"
      namespace: kube-system
    loop:
    - aws-creds
    - azure-credentials
    - gcp-credentials
