---
- name: Run workload tasks for ACM Virt Management Demo
  when: ACTION == "provision" or ACTION == "create"
  ansible.builtin.include_tasks: workload.yml

- name: Run removal tasks for ACM Virt Management Demo
  when: ACTION == "destroy" or ACTION == "remove"
  ansible.builtin.include_tasks: remove.yml
