---
- name: Install workloads
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Install workloads
      when: workloads | default([]) | length > 0
      ansible.builtin.include_role:
        name: "{{ workload_loop_var }}"
      vars:
        ACTION: provision
      loop: "{{ workloads }}"
      loop_control:
        loop_var: workload_loop_var
