---
- name: Destroy workload(s)
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
  - name: Set destroy workload list
    ansible.builtin.set_fact:
      _remove_workloads: >-
        {{ remove_workloads
           if (remove_workloads | default([]) | length > 0)
           else (workloads | default([]) | reverse | list) }}

  - name: Set workloads to remove in standard format
    loop: "{{ _remove_workloads }}"
    loop_control:
      label: "{{ _workload.name }} on {{ _clusters | join(',') }}"
    vars:
      _workload: "{{ item if item is mapping else {'name': item} }}"
      _clusters: "{{ _workload.clusters | default(['default']) }}"
    ansible.builtin.set_fact:
      _workloads: >-
        {{ _workloads | default([]) + [_workload | combine({"clusters": _clusters})] }}

  - name: Destroy workloads on cluster(s) using optimized destroyer role
    when: _remove_workloads | length > 0
    ansible.builtin.include_role:
      name: openshift_workload_destroyer
    vars:
      ACTION: destroy
      openshift_workload_destroyer_workloads: "{{ _workloads }}"
      openshift_workload_destroyer_clusters: "{{ clusters }}"
