---
name: build-ee-legacy-rhel-pr

on:
  pull_request_target:
    paths:
    - tools/execution_environments/ee-multicloud-legacy-rhel/**

jobs:
  build-and-push:
    concurrency:
      group: legacy-rhel-pr-${{ github.event.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment: ee-build

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-python@v4

      - name: Cache Buildah layers
        uses: actions/cache@v4
        with:
          path: /var/lib/containers/storage
          key: ${{ runner.os }}-buildah-cache-legacy-rhel-${{ hashFiles('tools/execution_environments/ee-multicloud-legacy-rhel/Containerfile', 'tools/execution_environments/ee-multicloud-legacy-rhel/requirements.*') }}
          restore-keys: |
            ${{ runner.os }}-buildah-cache-legacy-rhel-

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        id: build-image
        with:
          image: ee-multicloud-legacy-rhel
          tags: temporary-pr-${{ github.event.number }} ${{ github.sha }}
          labels: |
            quay.expires-after=7d
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.event.pull_request.head.sha }}
          platforms: linux/amd64
          context: tools/execution_environments/ee-multicloud-legacy-rhel
          containerfiles: |-
            tools/execution_environments/ee-multicloud-legacy-rhel/Containerfile
          layers: true
          build-args: |
            AAP_CERTIFIED_TOKEN=${{ secrets.AAP_CERTIFIED_TOKEN }}
            AAP_VALIDATED_TOKEN=${{ secrets.AAP_VALIDATED_TOKEN }}

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/redhat-gpte
          username: ${{ secrets.QUAY_REDHAT_GPTE_LEGACY_USER }}
          password: ${{ secrets.QUAY_REDHAT_GPTE_LEGACY_TOKEN }}
