---
name: Static Checks Push

on:
  push:
    branches:
    - main
    tags:
    - v*

jobs:
  static-checks:
    name: Run static tests using tox (Push)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.12'

    steps:
    - name: Get Repository Code
      id: get_repo_code
      uses: actions/checkout@v7

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run static checks
      run: |
        pip install tox
        tox -c tests/static

  all_checks_complete:
    needs: [static-checks]
    runs-on: ubuntu-latest
    steps:
    - run: echo "All checks passed!"        
...